# Generated by Django 4.1 on 2022-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forumpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='role',
            field=models.CharField(default='None', max_length=140),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='role',
            field=models.CharField(default='None', max_length=14),
        ),
    ]
