# Generated by Django 4.1 on 2022-10-29 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_event_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='range',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
