# Generated by Django 4.1 on 2022-10-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_events_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
