# Generated by Django 4.1 on 2022-11-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('notes', models.TextField(default='')),
            ],
        ),
    ]
